### ISSUE TITLE
Presence detection

### ISSUE THREAD

**Issue by humarf** [gitbock/fritzboxtr064#10]
Hello,

I just installed this new fritzbox addon. While wifi switch is working well (so I presume general setup is ok) I have problems with presence detection. I have defined an item for my mobile:

`Contact Martin     "Martin [MAP(presence.map): %s]"        <present>   (Mobiles, Status)   {fritzboxtr064="maconline:BC-F5-AC-E2-24-2B"}`

Mac adress is fine. I copied it directly from fritzbox wifi list just flipping ":" to "-". No matter if it is connected or not status is always "not present". Any idea what I could do?

I have installed:
org.openhab.binding.fritzboxtr064_1.8.0.201601021955.jar
openhab-1.8.1
oracle-jre-bin-1.8.0.74

Thanks and best regards
Martin

**Comment by gitbock** [comment]
Hi,

please check if you affected by the firtbox bug discussed in https://github.com/gitbock/fritzboxtr064/issues/1 
Your config looks fine.

Regards
Boris.

**Comment by humarf** [comment]
Thanks for your reply. Indeed I changed device name in fritzbox webui. After deleting the device presence detection is working. Maybe it's worth to put this into the manual.

Best regards
Martin
