### ISSUE TITLE
maconline not working with 7490 V.6.60

### ISSUE THREAD

**Issue by bugariu** [gitbock/fritzboxtr064#21]
Used version: 1.8.3

openhab.log says "Cannot retrieve item MasterAtHome for widget org.openhab.model.sitemap.Text"

MasterAtHome is defined as described in the wiki. Tested also with lower-cas MAC address but no change.

Callinfo seems also to not work. Definitely working: WLAN stati and the software version.

If you need additional information please ask.

**Comment by bbock** [comment]
maconline is working for me, on 7490 v6.60.

My item config looks like this:
```
Contact Bernhard "Bernhard [MAP(presence.map):%d]" <present> {fritzboxtr064="maconline:AA-BB-CC-DD-EE-FF"}
```

How is your definition of MasterAtHome ?

**Comment by bugariu** [comment]
Items file:
Contact MasterOnline "Presence (WiFi) [%s]" (FritzBox) {fritzboxtr064="maconline:AA-BB-CC-DD-EE-FF" }

Sitemap:
Group item=FritzBox icon="contact"
Which remains empty

It's also a 7490 with 6.60

**Comment by M-ax-G** [comment]
@bugariu : I cannot see a group label in your example.
E.g. your item has no hint of the group FritzBox (item is not a member of the group).

**Comment by bugariu** [comment]
Switched to 2.2 a few days ago. Will close the ticket
