### ISSUE TITLE
Tr064 binding on Synology doesn't work

### ISSUE THREAD

**Issue by PhilW35** [gitbock/fritzboxtr064#3]
Runnung my OH on a synology and tried to implement your binding in every way but it doesn't start anyhow. If I do the same procedure and settings on my Win7 OH it runs fine. Going back to the Syn everything else (homematic, FritzAHA, ntp, etc...) worked except the TR064 binding. Nothing to see in the log files or console.
I installed everything new, OH (from 1.7.0 to 1.7.1, write a new openhab.cfg)
Strange...Do you have an idea??

**Comment by gitbock** [comment]
Unfortunately you are the second one who is reporting such issues on a synology platform. It's a pitty that nothing useful is in the logs. Your forerunner even said, the binding is not logging any information when using the debug setting :(
One thing I can think of is, that the synology does not solve one of the required dependecies. But even this should not be the case as it's pure java and all other bindings are running. I will review my binding activate code and compare it to a binding which is running fine (ntp)

**Comment by PhilW35** [comment]
Also no logging anything in the debug...
But ok, give me the feeling that I'm not the problem ;-)
thx

**Comment by gitbock** [comment]
@PhilW35 
Niklas reported that the binding is starting on his server when he updated to java 1.8.0. You may have a look at issue #4 if you are interested...

**Comment by PhilW35** [comment]
THX, yes with java 8 it works... great...

**Comment by gitbock** [comment]
Thanks for your feedback! You are welcome :)
