### ISSUE TITLE
Binding does not start

### ISSUE THREAD

**Issue by niklasdoerfler** [gitbock/fritzboxtr064#4]
Hey,
I have a similar problem like the guys with the synology, but I'm using openHAB on a common PC running Linux (Ubuntu Server). 
Also I'm not able to see any logging of the bind, even if I enable the debug log output.

It would be nice if you could solve this issue :)

Thanks in advance
Niklas

**Comment by gitbock** [comment]
Try the following to start debugging the issue

1) 
connect to the osgi console by typing

```
telnet 127.0.0.1
```

and then look if the binding is listed and ACTIVE by typing

```
ss org.openhab.binding
```

2)
in the console try to start the binding manually by typing

```
start <bundle id>
```

3)
check your java version

```
java -version
```

Don't know exactly if it makes a difference, but on version 1.8.0 the binding it is running well. If you have a lower version, consider upgrading and testing with a newer version.

4)
Did you start your openHAB by using start_debug.sh? If yes, make sure you added the debug statement into the logback_debug.xml as well.

5)
Rise the debug level of the openHAB core by editing the logback.xml/logback_debug.xml:

```
<logger name="org.openhab" level="DEGUG"/>
```

**Comment by niklasdoerfler** [comment]
Thank you for your fast and detailed answer! I've updated Java to version 1.8 and now the binding is working :+1: 

But now I found another problem. I'm trying to control some lights depending on the presence of a smartphone. Therefore I created an item (as described in the readme) with the correct MAC-Address, but openHAB always shows "_not connected_", although the device is marked as online in the FRITZ!Box homenetwork-overview (using a FRITZ!Box 7490).

Furthermore I tried the perl script on your blog (https://www.bock-systems.de/?p=161), which shows "_Mac 1C:7B:21:xx:xx:xx not found in FritzBox Database!_"

So perhaps, the FRITZ!Box interface has changed? Or is something wrong with my configuration?

**Comment by gitbock** [comment]
Glad that it's starting now!

If you even tried the script already and it's reporting the same as the binding, you are affected by the FritzBox bug which reports a MAC as offline by the API.
To double check you may enable debug logging for the binding and watch for the raw SOAP responses from the fritzbox in the log file.

You may try the fixes I suggested in issue #1

**Comment by niklasdoerfler** [comment]
Great, it is working now :+1: 
I had to delete all network device manually in the FRITZ!Box "Netzwerkübersicht". 
After reconnecting them to the WiFi-Network, the binding shows the correct status.

Thank you for your good support! :)

**Comment by gitbock** [comment]
Thanks for your feedback!
You are welcome :)
