### ISSUE TITLE
Needs jdk1.8.0_65

### ISSUE THREAD

**Issue by ghost** [gitbock/fritzboxtr064#5]
Funktioniert bei mir nur mit jdk1.8.0_65 32bit/Hardfloat.
Mit Version openJDK 7 bekomme ich das Binding nicht zum Laufen.

Siehe auch der Hinweis in der openHAB Doku: dort wird empfohlen Oracle JDK 8 zu nehmen.
Sonst laufen einige Bindings nicht.
Vielleicht am Besten als Notiz vermerken. Erspart einigen viel Zeit ;-)

Getestet mit Fritzbox 7360 Fritz OS 6.30

**Comment by gitbock** [comment]
Danke für Deinen Hinweis. Ich habe es in die Readme mit aufgenommen. Es gab auch schon zwei Issues, die davon berichtet haben.
