### ISSUE TITLE
Jar missing in openhab-addons

### ISSUE THREAD

**Issue by quackes** [gitbock/fritzboxtr064#6]
The snapshot build for openhab-addons 1.8.0 does not contain the fritzboxtr064 jar as mentioned in the doc (https://github.com/openhab/openhab/wiki/FritzBox-TR064-Binding)
https://openhab.ci.cloudbees.com/job/openHAB/

Maybe missing Jenkins config.

**Comment by paphko** [comment]
Seems to be fixed with release 1.8.2

**Comment by gitbock** [comment]
Thanks!
