### ISSUE TITLE
Items with Callmonitor not working

### ISSUE THREAD

**Issue by frost80** [gitbock/fritzboxtr064#9]
Hi, 
i have a FB 6360 UM and testet the new addon. 
The first items (fboxWifi24, fboxName) work fine. 
But all items with callmonitor are not working.

My items:
String  fboxName            "FBox Model [%s]"           {fritzboxtr064="modelName"}
Switch  fboxWifi24           "2,4GHz Wifi"                   {fritzboxtr064="wifi24Switch"}

Switch  fboxRinging            "Phone ringing [%s]"                       {fritzboxtr064="callmonitor_ringing" }
Call      fboxIncomingCall    "Incoming call: [%1$s to %2$s]"     {fritzboxtr064="callmonitor_ringing" }
Call      fboxOutgoingCall    "Outgoing call: [%1$s to %2$s]"     {fritzboxtr064="callmonitor_outgoing" }

My sitemap:
Text    item=fboxName
Switch item=fboxWifi24
Switch item=fboxRinging
Text    item=fboxIncomingCall 
Text    item=fboxOutgoingCall

When i start openhab there comes an Error:
[ERROR] [o.o.b.f.i.FritzboxTr064Binding:545  ] - No tr064 service found for service id urn:WLANConfiguration-com:serviceId:WLANConfiguration3

then the Info:
[INFO ] [.service.AbstractActiveService:169  ] - FritzboxTr064 Refresh Service has been started

and i can see 
fboxWifi24 state updated to ON.

It works up to here.

But when i open the openhab app, there are many errors:
Item 'fboxRinging' could not be found in the item registry
10:16:25.797 [ERROR] [o.u.i.items.ItemUIRegistryImpl:438  ] - Cannot retrieve item fboxRinging for widget org.openhab.model.sitemap.Switch
10:16:25.797 [ERROR] [o.u.i.items.ItemUIRegistryImpl:438  ] - Cannot retrieve item fboxRinging for widget org.openhab.model.sitemap.Switch
10:16:25.797 [ERROR] [o.u.i.items.ItemUIRegistryImpl:438  ] - Cannot retrieve item fboxRinging for widget org.openhab.model.sitemap.Switch
10:16:25.797 [DEBUG] [o.i.r.i.resources.ItemResource:247  ] - Item 'fboxIncomingCall' could not be found in the item registry
10:16:25.798 [ERROR] [o.u.i.items.ItemUIRegistryImpl:438  ] - Cannot retrieve item fboxIncomingCall for widget org.openhab.model.sitemap.Text
10:16:25.798 [ERROR] [o.u.i.items.ItemUIRegistryImpl:438  ] - Cannot retrieve item fboxIncomingCall for widget org.openhab.model.sitemap.Text
10:16:25.798 [ERROR] [o.u.i.items.ItemUIRegistryImpl:438  ] - Cannot retrieve item fboxIncomingCall for widget org.openhab.model.sitemap.Text
10:16:25.799 [DEBUG] [o.i.r.i.resources.ItemResource:247  ] - Item 'fboxOutgoingCall' could not be found in the item registry
10:16:25.800 [ERROR] [o.u.i.items.ItemUIRegistryImpl:438  ] - Cannot retrieve item fboxOutgoingCall for widget org.openhab.model.sitemap.Text
10:16:25.801 [ERROR] [o.u.i.items.ItemUIRegistryImpl:438  ] - Cannot retrieve item fboxOutgoingCall for widget org.openhab.model.sitemap.Text
10:16:25.801 [ERROR] [o.u.i.items.ItemUIRegistryImpl:438  ] - Cannot retrieve item fboxOutgoingCall for widget org.openhab.model.sitemap.Text

Callmonitor is activated by telephone

Openhab Version 1.8
Fritzbox 6360 Version 06.04
For testing i installed openhab only with the fritzboxfritzboxtr064 binding. No other bindings that may cause problems.

Anyone an idea?

**Comment by gitbock** [comment]
Hi,

I guess the error 

```
No tr064 service found for service id urn:WLANConfiguration-com:serviceId:WLANConfiguration3
```

is shown because your Fbox either does not support 5GHz WLAN or no Guest WLAN (?) This is ok.

Did you turn on debugging and watch the log file? See [here](https://github.com/gitbock/fritzboxtr064/blob/master/README.md)

Also try to swap the order in your items file (just for testing): make the callmonitor items the first items and then the other fbox items. I was experiencing a similar problem where the last items were not loaded because of a syntax error.

**Comment by frost80** [comment]
Thanks very much for the answer. 
I swap the items and everything works fine.  And when i swap it back, it works too... 
I don't understand why but it works.

Only the first error after starting openhab is still there:
No tr064 service found for service id urn:WLANConfiguration-com:serviceId:WLANConfiguration3

This is because my Fbox doesn’t support 5 GHz Wlan? 
I have no items declared with features that aren't supported by my FB.

Debugging is turned on, but i can't see more errors.

**Comment by gitbock** [comment]
I'm glad it's working now. I guess it was a kind of syntax-typo in your item file.

I will lower the severity of the message from "error" to an "info" in the next release. This message is only shown when the binding starts: it evaluates all TR064 services in the beginning and checks if the fbox offers a service for the WLAN 5GHz switch. No need to worry.
